services:
  server:
    image: user_service
    env_file: .env
    ports:
    - 8080:8080
    depends_on:
     - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
