services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - ${PORT}:${PORT}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
