name: Test and coverage

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up .env file
        run: cp .env.example .env

      - name: Run tests with postgres
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose-test.yaml"

      - name: Copy the coverage output to the host
        run: docker cp user-service-service-1:/usr/src/app/coverage.out ./coverage.out
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
