name: Lint

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
          args: --timeout 1m
