name: Test compose.prod.yml

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          export EMAIL=${{ secrets.EMAIL }}
          export EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}"
          export SECRET_KEY=${{ secrets.SECRET_KEY }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t user-service  .
          echo "IMAGE_URI=user-service" > .env

      - name: Run docker compose up
        run: |
          docker network create traefik-shared
          docker compose -f compose.prod.yml up -d

      - name: Check if the service is still running
        run: |
          set -e
          sleep 5
          # For debugging
          docker ps
          docker ps | grep user-service-api-1
