name: Test compose.prod.yml

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.prod -t user-service  .

      - name: Set up environment variables
        run: |
          # Export the variables
          export EMAIL=${{ secrets.EMAIL }}
          export EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}"
          export SECRET_KEY=${{ secrets.SECRET_KEY }}
          
          # Save them to .env
          echo "IMAGE_URI=user-service" >> .env
          echo "EMAIL=$EMAIL" >> .env
          echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> .env
          echo "SECRET_KEY=$SECRET_KEY" >> .env
          touch firebase_private_key.json
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > firebase_private_key.json

      - name: Run docker compose up
        run: |
          docker network create traefik-shared
          docker compose -f compose.prod.yml up -d

      - name: Check if the service is still running
        run: |
          set -e
          sleep 5
          # For debugging
          docker ps
          docker logs user-service-api-1
          docker ps | grep user-service-api-1
